yutannihilation/savvy

savvy/src/sexp/integer.rs
savvy/src/sexp/logical.rs
savvy/src/sexp/real.rs
savvy/src/sexp/scalar.rs
savvy/src/sexp/string.rs

Close #18 
String is an exception.

Always create slice for real, integer, and bool

---

R-package/src/rust/src/lib.rs
R-package/src/rust/src/unwind.rs
README.md
README.qmd
docs/design.md
savvy/src/lib.rs
savvy/src/sexp/integer.rs
savvy/src/sexp/list.rs
savvy/src/sexp/logical.rs
savvy/src/sexp/real.rs
savvy/src/sexp/string.rs

Wrap fallible R API calls: Rf_allocVector()

---

savvy-bindgen/src/gen/rust.rs
savvy-bindgen/src/lib.rs
savvy-bindgen/src/parse_file.rs
savvy-bindgen/src/savvy_fn.rs
savvy-bindgen/src/savvy_impl.rs
savvy-macro/Cargo.toml
savvy-macro/src/lib.rs
savvy-macro/tests/cases/simple_cases.rs
savvy-macro/tests/cases/simple_cases.stderr
savvy-macro/tests/trybuild.rs

Minimum implementation for propagating macro errors

---

R-package/src/init.c
R-package/src/rust/api.h
savvy-bindgen/src/gen/c.rs

Add void to 0-arg signatures

---

.github/workflows/generate_pkg.yml
.github/workflows/wasm.yaml
R-package/DESCRIPTION
R-package/src/Makevars webr

TODO: How can I test the package on CI?
Related to #46

Test webr build on CI

---

R-package/src/Makevars.webr
R-package/src/rust/Cargo.toml

Reverts yutannihilation/savvy#49

Revert "Set panic = "abort""

---

savvy/src/sexp/integer.rs
savvy/src/sexp/logical.rs
savvy/src/sexp/real.rs

Skip unnecessary initialization

---

build.rs
src/unwind_protect.rs

* Do not `unwind_protect()` on wasm32

Support WebR

---

build.rs
src/unwind_protect.rs

Reverts yutannihilation/savvy#72
It turned out this is the issue in my compilation settings, not the code.

Revert "Support WebR"

---

CHANGELOG.md
R-package/R/wrappers.R
R-package/src/init.c
R-package/src/rust/api.h
R-package/src/rust/src/function.rs
R-package/tests/testthat/test-function.R
src/lib.rs
src/sexp/function.rs
src/sexp/list.rs

Use pairlist to handle function args

---

savvy-cli/src/main.rs
savvy-cli/src/utils.rs

Convert to snake_case

---

.github/workflows/release.yml

Since allow-dirty is true, the CI setting is not updated automatically.

Fix cargo-dist

---

src/sexp/external_pointer.rs
src/sexp/mod.rs
src/sexp/string.rs
src/unwind_protect.rs

Address unsafe_op_in_unsafe_fn lint

---

CHANGELOG.md
src/sexp/mod.rs

 Add get_dim() and set_dim() to Sexp 

---

CHANGELOG.md
src/sexp/mod.rs

Remove is_environment()

---

CHANGELOG.md
savvy-macro/src/lib.rs
src/sexp/complex.rs
src/sexp/external_pointer.rs
src/sexp/function.rs
src/sexp/integer.rs
src/sexp/list.rs
src/sexp/logical.rs
src/sexp/mod.rs
src/sexp/real.rs
src/sexp/string.rs
src/sexp/utils.rs

Refactor related to type assertions

---

R-package/src/rust/src/consuming_type.rs
R-package/tests/testthat/test-consuming_types.R
savvy-bindgen/src/gen/c.rs
savvy-bindgen/src/gen/r.rs
savvy-bindgen/src/gen/rust.rs
savvy-bindgen/src/savvy_fn.rs
savvy-bindgen/src/savvy_impl.rs

Allow consuming self

---

book/src/10_struct.md

Update the guide about user-defined struct

---

CHANGELOG.md
src/sexp/complex.rs
src/sexp/integer.rs
src/sexp/logical.rs
src/sexp/real.rs
src/sexp/string.rs

Implement try_from_slice()

---

book/src/01_get_started.md

Close https://github.com/yutannihilation/savvy/issues/155

Update Get Started section to install x86_64-pc-windows-gnu target

---

.cargo/config.toml
.github/workflows/R-CMD-check.yaml
savvy-bindgen/src/ir/mod.rs
savvy-bindgen/src/parse_file.rs
savvy-cli/src/main.rs
src/sexp/integer.rs

Part of https://github.com/yutannihilation/savvy/issues/20

Extract doctest

---

savvy-cli/Cargo.toml
savvy-cli/src/main.rs

Use async-process

---

.gitignore
CHANGELOG.md
R-package/src/Makevars.in
R-package/src/Makevars.win
savvy-bindgen/src/gen/templates/Makevars.in
savvy-bindgen/src/gen/templates/Makevars.win

Debug build

---

.github/workflows/R-CMD-check.yaml
CHANGELOG.md
savvy-bindgen/Cargo.toml
savvy-bindgen/src/ir/mod.rs
savvy-bindgen/src/lib.rs
savvy-bindgen/src/parse_file.rs
savvy-cli/Cargo.toml
savvy-cli/src/main.rs
src/sexp/integer.rs

Extract test module

---

R-package/src/Makevars.in
savvy-bindgen/src/gen/templates/Makevars.in

Since this is chosen based on the profile, it's not a problem to specify both.

Always use panic=abort for WebR

---

CHANGELOG.md
CONTRIBUTING.md
savvy-bindgen/src/gen/static_files.rs
savvy-bindgen/src/gen/templates/Cargo_toml
savvy-cli/src/main.rs

Do not rely on savvy R package for testing

---

.github/workflows/R-CMD-check.yaml
book/src/test.md
savvy-bindgen/src/gen/templates/Cargo_toml
savvy-cli/Cargo.toml
savvy-cli/src/main.rs
savvy-cli/src/parse_manifest.rs
savvy-cli/src/utils.rs

Parse Cargo.toml properly

---

.github/workflows/generate_pkg.yml
savvy-bindgen/src/gen/templates/lib_rs

Add test examples in the template

---

CHANGELOG.md
R-package/src/rust/src/altrep.rs
book/src/altrep.md
book/src/initialization_routine.md
savvy-bindgen/src/ir/savvy_fn.rs
savvy-bindgen/src/parse_file.rs
savvy-macro/src/lib.rs
savvy-macro/tests/cases/simple_cases.rs
savvy-macro/tests/cases/simple_cases.stderr
src/lib.rs

Re-introduce #[savvy_init]

---

.cargo/config.toml
CHANGELOG.md
Cargo.toml
R-package/src/rust/src/lib.rs
book/src/test.md
savvy-bindgen/src/gen/templates/lib_rs
savvy-bindgen/src/parse_file.rs
src/eval.rs
src/sexp/integer.rs

Use custom cfg instead of custom feature for `savvy-cli test`

---

R-package/R/000-wrappers.R
savvy-bindgen/src/gen/r.rs

Escape variables in the R wrapper file

---

.github/workflows/check-non-api.yaml
CHANGELOG.md
savvy-ffi/src/lib.rs
src/altrep/altstring.rs
src/sexp/environment.rs
xtask/src/main.rs

Eliminate the use of non-APIs

---

savvy-ffi/src/lib.rs
src/eval.rs
xtask/src/main.rs

Suggested in https://github.com/yutannihilation/savvy/issues/278#issuecomment-2239397890

refactor: Use R_ParseEvalString()

---

book/src/struct.md

Add some notes about struct with lifetimes

---

CHANGELOG.md
R-package/configure
savvy-bindgen/src/gen/templates/configure

* Check cargo command
* Print the version of `cargo` and `rustc`

Improve configure

---

.gitignore
CHANGELOG.md
R-package/cleanup.win
R-package/configure.win
R-package/src/Makevars.win.in
book/src/get_started.md
savvy-bindgen/src/gen/static_files.rs
savvy-bindgen/src/gen/templates/Makevars.win.in
savvy-bindgen/src/gen/templates/cleanup.win
savvy-bindgen/src/gen/templates/configure.win
savvy-bindgen/src/gen/templates/gitignore
savvy-bindgen/src/lib.rs
savvy-cli/src/main.rs

Context: https://github.com/yutannihilation/savvy/pull/294#issuecomment-2337929252

Add configure.win and cleanup.win

---

R-package/configure
R-package/configure.win
savvy-bindgen/src/gen/templates/configure
savvy-bindgen/src/gen/templates/configure.win

Fix Rust installation check in configure scripts

---

CHANGELOG.md
savvy-cli/src/main.rs
savvy-cli/src/utils.rs

Reject dot-containing package name

---

src/sexp/list.rs
src/sexp/logical.rs
src/sexp/numeric.rs
src/sexp/string.rs

c.f. https://rust-lang.github.io/rust-clippy/master/index.html#/needless_lifetimes

Fix clippy::needless_lifetimes

---

.github/workflows/wasm_and_arm64.yaml

ci: workaround cc 1.2.8 build issue for wasm target

---

.github/workflows/wasm_and_arm64.yaml
Cargo.toml

https://github.com/rust-lang/cc-rs/releases/tag/cc-v1.2.9

Use cc v1.2.9

---

R-package/R/000-wrappers.R
savvy-bindgen/src/gen/r.rs

Add a blank line after printing enum

---

CHANGELOG.md
R-package/src/Makevars.in
R-package/src/Makevars.win.in
savvy-bindgen/src/gen/templates/Makevars.in
savvy-bindgen/src/gen/templates/Makevars.win.in

Address https://github.com/yutannihilation/savvy/issues/355#issuecomment-2740111502

Make sure clean_intermediate is executed after "$(SHLIB)" is created

---

.github/workflows/release.yml
dist-workspace.toml

https://github.com/axodotdev/cargo-dist/releases/tag/v0.29.0

chore: Update cargo-dist to v0.29.0
