yutannihilation/savvy

.cargo/config.toml
.github/workflows/R-CMD-check.yaml
Cargo.toml
R-package/src/rust/Cargo.lock
R-package/src/rust/Cargo.toml
R-package/src/rust/src/error_handling.rs
rlang-ffi-lite/Cargo.toml
rlang-ffi-lite/src/lib.rs
savvy/Cargo.toml
savvy/src/error.rs
savvy/src/lib.rs
savvy/src/protect.rs
savvy/src/sexp/external_pointer.rs
savvy/src/sexp/integer.rs
savvy/src/sexp/list.rs
savvy/src/sexp/logical.rs
savvy/src/sexp/mod.rs
savvy/src/sexp/na.rs
savvy/src/sexp/null.rs
savvy/src/sexp/real.rs
savvy/src/sexp/scalar.rs
savvy/src/sexp/string.rs
savvy/src/unwind_protect.rs
wrapper.h
xtask/Cargo.toml
xtask/src/main.rs

Since the savvy framework uses only a subset of APIs, a simpler one is a better fit. Let's handcraft the minimal definitions.
`xtask` is added for verifying and updating the definitions. This design is inspired by pyo3's structure.

Create rlang-ffi-lite crate to replace libR-sys

---

R-package/src/Makevars.webr
R-package/src/rust/Cargo.toml

Since the savvy framework doesn't rely on panic, let's give up recovering from panic and reduce the binary size.

Set panic = "abort"

---

R-package/R/wrappers.R
R-package/src/init.c
R-package/src/rust/api.h
R-package/src/rust/src/lib.rs
R-package/src/rust/src/try_from.rs
R-package/tests/testthat/_snaps/custom-type.md
R-package/tests/testthat/test-custom-type.R
savvy-bindgen/src/savvy_fn.rs
savvy-macro/tests/cases/simple_cases.rs
savvy-macro/tests/cases/simple_cases.stderr

Do not check input and allow arbitrary types as long as it implements `TryFrom<Sxp>`

Allow arbitrary type of input

---

savvy/src/sexp/integer.rs
savvy/src/sexp/list.rs
savvy/src/sexp/logical.rs
savvy/src/sexp/real.rs
savvy/src/sexp/string.rs

[R-exts](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Allocating-storage) says:
>  One distinction is that whereas the R functions always initialize the elements of the vector, `allocVector` only does so for lists, expressions and character vectors (the cases where the elements are themselves R objects). 
But I forgot to implement it. cpp11 initializes by using `SET_ELT_*()`. But, as the SEXP allocated by `Rf_allocVector()` should be supposed to be non-ALTREP, we should be able to manipulate the underlying memory directly.

Initialize SEXP allocated by Rf_allocVector

---

savvy/src/sexp/integer.rs
savvy/src/sexp/logical.rs
savvy/src/sexp/real.rs

I'm not really sure if pursuing speed is worth here. But, probably this is not very dangerous to use.
https://doc.rust-lang.org/std/ptr/fn.write_bytes.html

Use std::ptr::write_bytes() for initialization

---

CHANGELOG.md
R-package/src/rust/src/convert_from_rust_types.rs
R-package/src/rust/src/error_handling.rs
R-package/src/rust/src/lib.rs
R-package/src/rust/src/try_from.rs
savvy/docs/design.md
savvy/src/io.rs
savvy/src/lib.rs

Note: I'm not really sure if `Rprintf()` and `REprintf()` is infallible, but, for ergonomics, it's a bit frustrating to always add `?` or `unwrap()` to the macro. So, let's assume they are infallible.

Make r_print() and r_eprint() to macro

---

CHANGELOG.md
R-package/src/rust/src/lib.rs
src/lib.rs
src/sexp/external_pointer.rs
src/sexp/mod.rs

While this is not recommended, I found there's no option other than this when we deal with external pointers created outside.

Implement ExternalPointerSexp

---

CHANGELOG.md
src/sexp/integer.rs
src/sexp/real.rs

This code always panics because the length of `out` is 0. I could set it by `set_len()`, but probably it's not worth having my own implementation here. Let's rely on the standard `to_vec()`.
```rust
let mut out = Vec::with_capacity(self.len());
out.copy_from_slice(self.as_slice());
out
```

Do not use copy_from_slice() for to_vec()

---

CHANGELOG.md
R-package/src/rust/src/attributes.rs
book/src/12_attributes.md
book/src/15_matrix.md
src/sexp/mod.rs

At the time of writing `get_dim()`, I thought `usize` is handy because the user anyway needs to convert to `usize` if it returns `i32`. But, after some thinking, I now feel it might not be always the case when the dim can be used as it is. For example, nalgebra takes two `usize` instead of a slice, so the allocation of the vector is not necessary.
```rust
/// @export
#[savvy]
fn nalgebra_input(x: RealSexp) -> savvy::Result<()> {
let dim = x.get_dim().ok_or("no dimension found")?;
if dim.len() != 2 {
return Err("Input must be matrix!".into());
}
let m = DMatrix::from_vec(dim[0], dim[1], x.to_vec());
r_println!("{m:?}");
Ok(())
}
```

Change the return type of get_dim() to Option<&[i32]>

---

savvy-ffi/src/lib.rs
src/lib.rs
src/sexp/mod.rs

Note: For some reason, the return type of TYPEOF() is defined as int in
RInternals.h and memory.c. However, the actual implementation is
In memory.c:
int (TYPEOF)(SEXP x) { return TYPEOF(CHK(x)); }
In Defn.h:
#define TYPEOF(x)    ((x)->sxpinfo.type)
and the definition of the `type` field of `sxpinfo_struct` is `SEXPTYPE`,
so the actual return type should be `SEXPTYPE`, while I'm not 100% sure...

Change the return type of TYPEOF() to SEXPTYPE

---

CHANGELOG.md
src/sexp/logical.rs

I found this is needed to construct polars' `BooleanChunked` from `LogicalSexp`

Expose LogicalSexp::as_slice_raw()

---

CHANGELOG.md
R-package/R/wrappers.R
R-package/src/init.c
R-package/src/rust/api.h
R-package/src/rust/src/consuming_type.rs
R-package/src/rust/src/lib.rs
R-package/tests/testthat/_snaps/consuming_types.md
R-package/tests/testthat/test-consuming_types.R
R-package/tests/testthat/test-invalid_pointer.R
savvy-bindgen/src/gen/r.rs
savvy-bindgen/src/savvy_fn.rs
savvy-macro/src/lib.rs
savvy-macro/tests/cases/simple_cases.rs
savvy-macro/tests/cases/simple_cases.stderr
src/error.rs
src/lib.rs
src/sexp/external_pointer.rs
src/sexp/mod.rs

Close #128
Example:
```rust
struct Value(i32);
#[savvy]
impl Value {
fn new(x: i32) -> Self {
Self(x)
}
}
struct ValuePair {
a: Value,
b: Value,
}
#[savvy]
impl ValuePair {
fn new(a: Value, b: Value) -> Self {
Self { a, b }
}
fn print(&self) -> savvy::Result<()> {
// ...snip...
}
}
```
``` r
a <- Value$new(1L)
b <- Value$new(2L)
pair <- ValuePair$new(a, b)  # a and b are consumed
pair$print()
#> ValuePair { a: Value(1), b: Value(2) }
pair <- ValuePair$new(a, b)  # you cannot use a or b anymore
#> Error: This external pointer is already consumed or deleted
```

Support consuming user-defined structs in input

---

CHANGELOG.md
R-package/R/wrappers.R
R-package/src/init.c
R-package/src/rust/api.h
R-package/src/rust/src/lib.rs
R-package/src/rust/src/try_from_iter.rs
R-package/tests/testthat/test-try_from_iter.R
savvy-ffi/src/lib.rs
src/sexp/complex.rs
src/sexp/integer.rs
src/sexp/logical.rs
src/sexp/real.rs
src/sexp/string.rs
xtask/src/main.rs

Implement try_from_iter()

---

src/sexp/logical.rs
src/sexp/mod.rs
src/sexp/string.rs

Remove some bounds check on `LogicalSexp` and `StringSexp` constructors. I didn't mess with the iterator part since I don't know if you are finished there yet, but `set_elt_unchecked` can probably be used there as well.
I also removed a nested unsafe in one of your functions.
I can't manage to test your crate. I don't know how to... But it compiles.

Optimize constructors for `LogicalSexp` and `StringSexp`

---

R-package/src/rust/src/consuming_type.rs
R-package/src/rust/src/lib.rs
savvy-bindgen/src/gen/templates/lib_rs
savvy-bindgen/src/lib.rs
savvy-bindgen/src/savvy_struct.rs
savvy-macro/src/lib.rs

This is a first step towards #118 and #149 
``` rust
#[savvy]   // NEW
struct Person {
pub name: String,
}
#[savvy]
impl Person {
```

Separate the implementation of `#[savvy]`'s TryFrom generation for a struct

---

src/sexp/list.rs
src/sexp/string.rs

Added 2 unsafe methods. This time I decided to make them public as it seems to be the better way in the case of `ListSexp`, since there are no constructors from slices (and I think it's better not to have them in this case).
I also signaled as unsafe other "unchecked" functions.
Please feel free to criticize and change the code at your will.

unsafe methods to set name and values of ListSexp

---

.github/workflows/R-CMD-check.yaml
.github/workflows/msrv.yaml
CHANGELOG.md
Cargo.toml
R-package/tests/testthat/test-panic.R
savvy-bindgen/src/gen/rust.rs
src/lib.rs
src/panic_hook.rs

Address #163 
In release build, `catch_unwind()` catches unwinding before the FFI boundary and aborts. Note that, while `panic!` should terminate the process in principle, it might be safe to throw R error and restart unwinding on R's side rather than aborting. But, I cannot make my mind at the moment.
In debug build (with `DEBUG=true`, i.e. in `devtools::load_all(".")`), panic no longer crashes the R session. It shows backtrace.
``` r
code <- r"(
use savvy::savvy;
#[allow(unreachable_code)]
#[savvy]
fn try_panic() -> savvy::Result<()> {
panic!("safe");
Ok(())
}
)"
savvy_override <- list(savvy = list(git = "https://github.com/yutannihilation/savvy", branch = "catch-panic"))
savvy::savvy_source(code, use_cache_dir = TRUE, dependencies = savvy_override)
try_panic()
#> panic occured!
#> 
#> …
```

Catch panic

---

CHANGELOG.md
src/sexp/complex.rs
src/sexp/integer.rs
src/sexp/logical.rs
src/sexp/real.rs
src/sexp/string.rs

`try_from_iter()` doesn't change the `len` stored in Rust's side. This PR fixes it. Tests will be added in the doctest later...

Fix try_from_iter()

---

CHANGELOG.md
savvy-cli/src/main.rs
savvy-macro/Cargo.toml

Pass `dependencies` variable to `savvy::savvy_source()`

Make savvy-cli use the local code

---

CHANGELOG.md
R-package/.Rbuildignore
book/src/get_started.md
savvy-cli/Cargo.toml
savvy-cli/src/main.rs

* Fix `savvy-cli test`
* `savvy-cli update` now updates `.Rbuildignore`
* Use OS's cache dir for `savvy-cli test` instead of `.savvy` directory (close #184)

Minor improvements about CLI

---

.github/workflows/R-CMD-check.yaml
CHANGELOG.md
savvy-cli/src/main.rs
savvy-cli/src/utils.rs
src/sexp/complex.rs

* `savvy-cli test` now picks `[dev-dependencies]` as the dependency.
* `savvy-cli test` got `--features` argument to add features to be used for testing.

Support dev-dependencies and --features

---

CHANGELOG.md
R-package/src/rust/src/lib.rs
book/src/test.md
savvy-macro/src/lib.rs

Make all function, struct, impl-items, and enum marked with `#[savvy]` public. This is for testing purposes.
Close #198

Always public

---

CHANGELOG.md
R-package/src/rust/src/lib.rs
book/src/test.md
savvy-bindgen/src/parse_file.rs
src/eval.rs
src/sexp/integer.rs

There can be two types of tests modules
* tests that need to be run by `savvy-cli test` (for a real R session)
* tests that need to be run by `cargo test` (for the usual testing behaviors like visibility)
so this needs a separate marker.

Use #[cfg(savvy_test)] instead of #[cfg(test)] for marking tests for savvy-cli test

---

book/src/struct.md
src/eval.rs
src/protect.rs
src/sexp/external_pointer.rs
src/sexp/function.rs
src/sexp/string.rs

Provide a protection that lasts within the function scope, i.e.,
automatically cleans up by `Rf_unprotect()`. This might not be very
efficient as this can execute `Rf_unprotect(1)` multiple times where it
could be `Rf_unprotect(n)` once. But, I found manual `Rf_unprotect()` is
almost impossible for human considering there are many early return by `?`,
so this should be better than failure.

Use Drop mechanism for managing PROTECT and UNPROTECT

---

savvy-cli/src/main.rs

Even if all the files are LF on local, it seems GitHub ACtions CI checks it out as CRLF on Windows runner, so replace CRLF to LF here just to make sure.

Ensure linebreak is LF

---

.github/workflows/check-non-api.yaml
CHANGELOG.md
savvy-ffi/src/lib.rs
src/sexp/complex.rs
src/sexp/integer.rs
src/sexp/logical.rs
src/sexp/real.rs
src/sexp/string.rs
xtask/src/main.rs

Close #209.
cf. https://fosstodon.org/@shikokuchuo/112325582047868252
But, the implementation is not efficient. Probably manual `Rf_allocVector()` + memcpy should faster. Or, maybe I can just `collect()` into a `Vec` first?
https://github.com/r-devel/r-svn/blob/faa2ca57cc03c26c49a5de39db980268c6c4cc67/src/main/builtin.c#L832C6-L832C17
Anyway, let's think about it later. I'd like to get rid of the CI error for now.

Do not use `SETLENGTH`

---

CHANGELOG.md
R-package/src/init.c
R-package/src/rust/api.h
R-package/src/rust/src/lib.rs
book/src/SUMMARY.md
book/src/initialization_routine.md
savvy-bindgen/src/gen/c.rs
savvy-bindgen/src/gen/r.rs
savvy-bindgen/src/gen/rust.rs
savvy-bindgen/src/ir/savvy_fn.rs
savvy-bindgen/src/lib.rs
savvy-bindgen/src/parse_file.rs
savvy-ffi/src/lib.rs
savvy-macro/src/lib.rs
savvy-macro/tests/cases/simple_cases.rs
savvy-macro/tests/cases/simple_cases.stderr
src/ffi.rs
xtask/src/main.rs

Close #208
If `#[savvy]` is placed on a function that takes `DllInfo` as argument, it's executed in the initialization routine. This is a bit tricky, but, in this way, I don't need to introduce another macro notation like `#[savvy_init]`.
Rust:
``` rust
#[savvy]
fn init_foo(_dll_info: *mut savvy::ffi::DllInfo) -> savvy::Result<()> {
r_eprintln!("Initialized!");
Ok(())
}
```
C:
``` c
void R_init_savvyExamples(DllInfo *dll) {
R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
R_useDynamicSymbols(dll, FALSE);
savvy_init_foo__impl(dll); // NEW!
}
```
R session:
```r
library(savvyExamples)
#> Initialized!
```

Support initialization

---

savvy-bindgen/src/ir/mod.rs
src/unwind_protect.rs

```
warning: assigning the result of `Clone::clone()` may be inefficient
--> savvy-bindgen\src\ir\mod.rs:97:21
|
97 |                     merged.docs = e.docs.clone();
|                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `clone_from()`: `merged.docs.clone_from(&e.docs)`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assigning_clones
= note: `#[warn(clippy::assigning_clones)]` on by default
warning: `savvy-bindgen` (lib) generated 1 warning
Compiling savvy-macro v0.6.1 (C:\Users\Yutani\Documents\GitHub\savvy\savvy-macro)
warning: transmute used without annotations
--> src\unwind_protect.rs:31:29
|
31 |         let fun = std::mem::transmute(fun_ptr);
|                             ^^^^^^^^^ help: consider adding missing annotations: …
```

Fix minor clippy warnings

---

R-package/R/000-wrappers.R
R-package/src/init.c
R-package/src/rust/api.h
R-package/src/rust/src/optional_arg.rs
R-package/tests/testthat/test-optional_args.R
savvy-bindgen/src/gen/r.rs

Handle `NULL` on an optonal struct argument

---

savvy-bindgen/src/gen/r.rs

I was just wondering about the spaces.
before:
```r
.savvy_wrap_RGlareDbConnection <- function(ptr) {
e <- new.env(parent = emptyenv())
e$.ptr <- ptr
e$sql <- RGlareDbConnection_sql(ptr)
e$prql <- RGlareDbConnection_prql(ptr)
e$execute <- RGlareDbConnection_execute(ptr)
class(e) <- "RGlareDbConnection"
e
}
```
after:
```r
.savvy_wrap_RGlareDbConnection <- function(ptr) {
e <- new.env(parent = emptyenv())
e$.ptr <- ptr
e$sql <- RGlareDbConnection_sql(ptr)
e$prql <- RGlareDbConnection_prql(ptr)
e$execute <- RGlareDbConnection_execute(ptr)
class(e) <- "RGlareDbConnection"
e
}
```
I'm afraid I just edited it on GitHub, so if you have any snapshot tests, etc., I'd appreciate it if you could update it.

refactor(bindgen): remove tab spaces

---

savvy-ffi/src/lib.rs
src/altrep/altlist.rs
src/altrep/altstring.rs
xtask/src/main.rs

* Do not cast the result of `STRING_PTR_RO` to `*mut T`; remove `Dataptr` method from `AltString`.
* Use `DATAPTR_RO` instead of `DATAPTR` (this should be `VECTOR_PTR_RO`, but since it's the API only available on R-deve, `DATAPTR_RO` is more handy for now).

Properly use the read-only version of API

---

src/altrep/mod.rs
src/eval.rs
src/protect.rs
src/sexp/complex.rs
src/sexp/external_pointer.rs
src/sexp/function.rs
src/sexp/integer.rs
src/sexp/logical.rs
src/sexp/raw.rs
src/sexp/real.rs
src/sexp/string.rs

fix usage of `local_protect()`

---

savvy-bindgen/src/ir/savvy_struct.rs
savvy-macro/tests/cases/simple_cases.rs
savvy-macro/tests/cases/simple_cases.stderr

Show better error message for https://github.com/yutannihilation/savvy/issues/281
```
error: #[savvy] macro doesn't support lifetime
--> tests/cases/simple_cases.rs:54:12
|
54 | struct Foo<'a>(External::Bar<'a>);
|            ^^
```

Reject lifetimed struct

---

Cargo.toml
src/panic_hook.rs

Close #282 
I might want to add some different implementation for `PanicHookInfo` when it gets more features, but this should be suffice for now to avoid the deprecation warning.

Use `std::panic::PanicHookInfo` for Rust >=1.81

---

CHANGELOG.md
savvy-ffi/src/lib.rs
src/sexp/environment.rs
xtask/src/main.rs

This replaces `Rf_findVarInFrame()` with `R_existsVarInFrame()` and `Rf_eval()`. This implementation isn't very efficient, but since savvy is not very eager to support environment, this should be enough for now. While I could use `cfg` to use different implementation for R >4.5 where `R_getVar()` is available, I chose to avoid make the implementation complex.

Remove `Rf_findVarInFrame`

---

R-package/configure
savvy-bindgen/src/gen/templates/configure

- Perhaps `-d` is more appropriate here than `-e`?
- This is not a Makefile, so if we leave these as `$()`, we may get an error because there are no commands `HOME` or `PATH`.

fix(bindgen/template): fix shell commands

---

savvy-bindgen/src/parse_file.rs
savvy-cli/Cargo.toml

Close #282 
I think I can introduce a `#[rustversion]` switch here, but, for the sake of simplicity, I chose to bump the MSRV of savvy-cli. This doesn't affect savvy.

Use PanicHookInfo in savvy-cli

---

CHANGELOG.md
R-package/tests/testthat/test-numeric.R
src/sexp/numeric.rs

This is a follow-up of #311 
A double precision floating point number has 53-bit significand precision(ref: [Wikipedia](https://en.wikipedia.org/wiki/Double-precision_floating-point_format)). So, if the number is equal to or larger than 2^53, it cannot be safely converted to u64.
It seems this is the strategy of JavaScript.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

Reject the conversion from >2^53 to usize 

---

CONTRIBUTING.md

The link to `pkgbuild` was borked as its markdown definition was (accidentally, I presume) set as `okgbuild`.

One-char typo fix to CONTRIBUTING.md

---

R-package/configure
R-package/configure.win
R-package/src/Makevars.in
R-package/src/Makevars.win.in
savvy-bindgen/src/gen/templates/Makevars.in
savvy-bindgen/src/gen/templates/Makevars.win.in
savvy-bindgen/src/gen/templates/configure
savvy-bindgen/src/gen/templates/configure.win

`subst` trick looks a bit too magical.

Handle `DEBUG` envvar in configure script rather than in Makevars

---

R-package/src/Makevars.in
R-package/src/Makevars.win.in
book/src/linkage.md
savvy-bindgen/src/gen/templates/Makevars.in
savvy-bindgen/src/gen/templates/Makevars.win.in

I use `cargo rustc --`, but extendr Discord told me `RUSTFLAGS` is better.

Use RUSTFLAGS to inject `--print=native-static-libs`

---

src/sexp/numeric.rs

IIUC, I don't think `usize::MAX` is guaranteed to be greater than 2^53-1.
(I am not sure if the name of the constant is appropriate, so feel free to edit it.)

fix: 2^53-1 may lager than usize::MAX

---

R-package/src/Makevars.in
R-package/src/Makevars.win.in
savvy-bindgen/src/gen/templates/Makevars.in
savvy-bindgen/src/gen/templates/Makevars.win.in

A follow up of https://github.com/yutannihilation/savvy/pull/357
`./rust/.cargo` and `./rust/vendor` are what are used when vendoring. This is not the case.

Do not clean non-existent directories

---

CHANGELOG.md
src/unwind_protect_wrapper.c

Close #368
When I ported the code in cpp11 to savvy, I couldn't understand why cpp11 doesn't cause memory leak without calling `R_ReleaseObject()`. Maybe is this a difference between C++ and Rust about stack unwinding...?
https://github.com/r-lib/cpp11/blob/05c888b0c6f49e7b252b79b028e4719e6d5b299d/inst/include/cpp11/protect.hpp#L42
Anyway, it seems savvy needs this to prevent memory leak.

Release continous token by R_ReleaseObject()

---

src/unwind_protect_wrapper.c

cf. https://bsky.app/profile/gaborcsardi.org/post/3lmznrhd3uc22
Fix #368
I was believing cpp11 uses `R_PreserveObject()` because `PROTECT()` doesn't work. But, it seems it does work.
I think `PROTECT()` is best if it works, because it automatically gets stack-unwound when longjmp. I don't fully understand the C/C++ things, but I think this is what is supposed to be.
Also, this pull request removes `SETCAR(token, R_NilValue)`. While cpp11 argues this is necessary to really release the continuous token, it seems the token gets GC-ed without doing it (It seems `CAR` of the continuous token is a length-1 of empty character vector). It might have been necessary in some older version of R? I don't know the details.

Use PROTECT() on continuous token

---

CHANGELOG.md
savvy-bindgen/src/gen/c.rs
savvy-bindgen/src/gen/r.rs
savvy-bindgen/src/parse_file.rs
src/sexp/integer.rs
src/sexp/list.rs
src/sexp/logical.rs
src/sexp/numeric.rs
src/sexp/raw.rs
src/sexp/real.rs
src/sexp/string.rs

Address this lint: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/lifetime_syntax/static.MISMATCHED_LIFETIME_SYNTAXES.html
Although the warning suggests to use an anonymous lifetime, the intention was that the iterator should have the same lifetime as `&self`. So, this pull request explicitly annotated it.
```
warning: lifetime flowing from input to output with different syntax can be confusing
--> src/sexp/logical.rs:55:17
|
55 |     pub fn iter(&self) -> LogicalSexpIter {
|                 ^^^^^     --------------- the lifetime gets resolved as `'_`
|                 |
|                 this lifetime flows to the output
|
= note: `#[warn(mismatched_lifetime_syntaxes)]` on by default
help: one option is to remove the lifetime for references and use the anonymous lifetime for …
```

Address `MISMATCHED_LIFETIME_SYNTAXES` lint

---

.github/workflows/R-CMD-check.yaml
R-package/.Rbuildignore
R-package/DESCRIPTION
R-package/bootstrap.R

https://pkgbuild.r-lib.org/reference/build.html:
> `Config/build/bootstrap` can be set to `TRUE` to run `Rscript bootstrap.R` in the source directory prior to running subsequent build steps.

Use bootstrap.R
